VERSION 05/10/2023 17:08:08
FIG #C:\Users\alexo\OneDrive\Documents\MasterNuevasTecnologiasElectronicasyFotonicas\DiseñodeCircuitosIntegrados\Inversor_TamañoOP.MS
BB(19,17,43,48)
SIMU #5.00
REC(25,38,4,8,ME)
REC(33,34,4,8,ME)
REC(25,21,12,4,DN)
REC(26,22,2,2,CO)
REC(30,35,2,10,PO)
REC(34,22,2,2,CO)
REC(26,39,2,2,CO)
REC(30,18,2,10,PO)
REC(34,39,2,2,CO)
REC(25,17,4,8,ME)
REC(25,38,12,4,DP)
REC(33,21,4,8,ME)
REC(19,32,24,16,NW)
FFIG C:\Users\alexo\OneDrive\Documents\MasterNuevasTecnologiasElectronicasyFotonicas\DiseñodeCircuitosIntegrados\Inversor_TamañoOP.MS
