VERSION 05/10/2023 16:21:06
FIG #C:\Users\alexo\OneDrive\Documents\MasterNuevasTecnologiasElectronicasyFotonicas\DiseñodeCircuitosIntegrados\Inversor_TamañoMin.M
BB(18,-1,42,31)
SIMU #5.00
REC(18,15,24,16,NW)
REC(31,21,5,4,DP)
REC(24,21,5,4,DP)
REC(31,3,5,4,DN)
REC(24,3,5,4,DN)
REC(33,4,2,2,CO)
REC(25,22,2,2,CO)
REC(25,4,2,2,CO)
REC(33,22,2,2,CO)
REC(29,0,2,28,PO)
REC(24,21,4,8,ME)
REC(24,-1,4,8,ME)
REC(32,3,4,22,ME)
REC(29,21,2,4,DP)
REC(29,3,2,4,DN)
TITLE 26 27  #Vdd
$1 1000 0 
TITLE 26 1  #Vss
$0 1000 0 
TITLE 30 13  #clock1
$c 1000 0 0.2250 0.2500 0.4750 0.5000 
TITLE 34 13  #s1
$v 1000 0 
FFIG C:\Users\alexo\OneDrive\Documents\MasterNuevasTecnologiasElectronicasyFotonicas\DiseñodeCircuitosIntegrados\Inversor_TamañoMin.M
